cinemafast/CinemasFAST/Models/acteur.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemasFAST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acteur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acteur()
        {
            this.roles = new HashSet<role>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string langue { get; set; }
        public System.DateTime date_naissance { get; set; }
        public string lieu_naissance { get; set; }
        public string image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<role> roles { get; set; }
    }
}

cinemafast/CinemasFAST/Controllers/acteursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CinemasFAST.Models;
using CinemasFAST.Models.ViewModels;

namespace CinemasFAST.Controllers
{
    public class acteursController : Controller
    {
        private cinemadbEntities db = new cinemadbEntities();

        // GET: acteurs
        public async Task<ActionResult> Index(bool? erreur, bool? erreurDel, string searchString)
        {
            if (erreur == true)
                ViewBag.erreur = "fail";
            else if (erreur == false)
                ViewBag.erreur = "succes";
            else
                ViewBag.erreur = "normal";
            if (erreurDel == null)
                erreurDel = true;
            ViewBag.erreurDel = erreurDel;

            IndexActeurs_ViewModel viewModel = new IndexActeurs_ViewModel();

            if (!String.IsNullOrEmpty(searchString))
            {
                viewModel.Acteurs = await db.acteurs.Where(s => s.nom.Contains(searchString)
                                       || s.prenom.Contains(searchString)).ToListAsync();
                ViewBag.searchRequest = true;
            }
            else
            {
                viewModel.Acteurs = await db.acteurs.ToListAsync();
                ViewBag.searchRequest = false;
            }

            ModelState.Clear();
            return View(viewModel);
        }

        // GET: acteurs/Details/5
        public ActionResult Details(int? id, bool? error)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (error == false)
                ViewBag.erreur = "Succes";
            else
                ViewBag.erreur = "normal";
            //remplis un viewmodel qui permetteras d'afficher les roles de l'acteur dans le details
            RolesDirections_ViewModel viewModel = new RolesDirections_ViewModel();
            acteur acteur = db.acteurs.Find(id);
            viewModel.Acteur = acteur;
            viewModel.Roles = db.roles.Where(r => r.id_acteur == id).ToList();
            if (viewModel.Acteur == null)
            {
                return HttpNotFound();
            }
            return View(viewModel);
        }

        // GET: acteurs/Create
        public ActionResult Create()
        {
            ViewBag.searchRequest = false;
            return View();
        }

        // POST: acteurs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,nom,prenom,langue,date_naissance,lieu_naissance,image")] acteur acteur)
        {
            bool isConflicted = false;
            if (ModelState.IsValid)
            {
                isConflicted = false;
                db.acteurs.Add(acteur);
                db.SaveChanges();
            }
            else
            {
                isConflicted = true;
            }
            return RedirectToAction("Index", new { erreur = isConflicted });
        }

        // GET: acteurs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            acteur acteur = db.acteurs.Find(id);
            if (acteur == null)
            {
                return HttpNotFound();
            }
            return View(acteur);
        }

        // POST: acteurs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,nom,prenom,langue,date_naissance,lieu_naissance,image")] acteur acteur)
        {
            if (ModelState.IsValid)
            {
                db.Entry(acteur).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = acteur.id, error = false });
            }
            //remplis un viewmodel qui permetteras d'afficher les roles de l'acteur dans le details
            RolesDirections_ViewModel viewModel = new RolesDirections_ViewModel();
            viewModel.Acteur = db.acteurs.Find(acteur.id);
            viewModel.Roles = db.roles.Where(r => r.id_acteur == acteur.id).ToList();
            return View(" ", viewModel);
        }

        // GET: acteurs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            acteur acteur = db.acteurs.Find(id);
            if (acteur == null)
            {
                return HttpNotFound();
            }
            return View(acteur);
        }

        // POST: acteurs/Delete/5
        public ActionResult DeleteConfirmed(int id)
        {
            List<role> roles = db.roles.Where(r => r.id_acteur == id).ToList();
            foreach (role r in roles)
            {
                db.roles.Remove(r);
            }
            acteur acteur = db.acteurs.Find(id);
            bool isConflicted = false;
            db.acteurs.Remove(acteur);
            db.SaveChanges();
            return RedirectToAction("Index", new { erreurDel = isConflicted });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult deleteRole(int id)
        {
            return RedirectToAction("DeleteConfirmedToActeur", "roles", new { id = id });
        }
    }
}

cinemafast/CinemasFAST/Views/acteurs/Create.cshtml
@model CinemasFAST.Models.acteur

@{
    ViewBag.Title = "Create";
}
<div class="jumbotron">
    <h2>Ajouter un acteur</h2>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="d-flex row table-light mb-4">
        <div class="form-horizontal col-4">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.prenom, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.prenom, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.prenom, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.langue, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.langue, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.langue, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-horizontal col-4">
            <div class="form-group">
                @Html.LabelFor(model => model.date_naissance, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.date_naissance, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.date_naissance, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.lieu_naissance, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.lieu_naissance, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.lieu_naissance, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <p class="ml-3">
        <button type="button" class="btn btn-dark">@Html.ActionLink("Retour", null, null, null, new { href = Request.UrlReferrer })</button>
        <input type="submit" value="Ajouter" class="btn btn-success" />
    </p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

cinemafast/CinemasFAST/Views/acteurs/Delete.cshtml
@model CinemasFAST.Models.acteur

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>acteur</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prenom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.langue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.langue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_naissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_naissance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lieu_naissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lieu_naissance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

cinemafast/CinemasFAST/Views/acteurs/Details.cshtml
@model CinemasFAST.Models.RolesDirections_ViewModel

@{
    ViewBag.Title = " ";
}

<div class="jumbotron">
    <h2>Acteur</h2>
    @if (ViewBag.erreur == "Succes")
    {
        <h4 class="text-success">Acteur modifié avec succès!</h4>
    }
</div>



<div>
    @Html.Partial("~/Views/acteurs/_Edit.cshtml", Model.Acteur)
</div>

<div class="jumbotron"><h2>Rôle</h2></div>

<div>
    @Html.Partial("~/Views/roles/_Index.cshtml", Model.Roles)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

cinemafast/CinemasFAST/Views/acteurs/Edit.cshtml
@model CinemasFAST.Models.acteur

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>acteur</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prenom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prenom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prenom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.langue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.langue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.langue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_naissance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_naissance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_naissance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lieu_naissance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lieu_naissance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lieu_naissance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enregistrer" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

cinemafast/CinemasFAST/Views/acteurs/Index.cshtml
@model CinemasFAST.Models.ViewModels.IndexActeurs_ViewModel

@{ ViewBag.Title = "Index"; }

<div>
    @Html.Partial("~/Views/acteurs/_Index.cshtml", Model.Acteurs)
</div>

<div>
    @Html.Partial("~/Views/acteurs/_Create.cshtml", new CinemasFAST.Models.acteur())
</div>

cinemafast/CinemasFAST/Views/acteurs/_Create.cshtml
@model CinemasFAST.Models.acteur

@using (Html.BeginForm("Create", "acteurs"))
{
    <div class="modal fade" id="acteurCreate" tabindex="-1" role="dialog" aria-labelledby="Longtitle3"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="Longtitle3">Ajouter un acteur</h5>
                    <h4 class="text-danger">@Session["createErreur"]</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control col-12" } })
                            @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.prenom, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.prenom, new { htmlAttributes = new { @class = "form-control col-12" } })
                            @Html.ValidationMessageFor(model => model.prenom, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.langue, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12">
                            @Html.DropDownList("langue", new List<SelectListItem>
                                                 { new SelectListItem { Text = "Anglais", Value = "Anglais", Selected=true},
                                                   new SelectListItem { Text = "Français", Value = "Français"},
                                                   new SelectListItem { Text = "Espagnol", Value = "Espagnol"},
                                                   new SelectListItem { Text = "Italien", Value = "Italien"},
                                                   new SelectListItem { Text = "Mandarin", Value = "Mandarin"},
                                                   new SelectListItem { Text = "Hindustani", Value = "Hindustani"},
                                                   new SelectListItem { Text = "Arabe", Value = "Arabe"},
                                                   new SelectListItem { Text = "Russe", Value = "Russe"},
                                                   new SelectListItem { Text = "Portugais", Value = "Portugais"},
                                                   }, new { @class = "form-control col-12" })
                            @Html.ValidationMessageFor(model => model.langue, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.date_naissance, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.date_naissance, new { htmlAttributes = new { @class = "form-control col-12" } })
                            @Html.ValidationMessageFor(model => model.date_naissance, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.lieu_naissance, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.lieu_naissance, new { htmlAttributes = new { @class = "form-control col-12" } })
                            @Html.ValidationMessageFor(model => model.lieu_naissance, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.image, new
                            {
                                htmlAttributes = new
                                {
                                    @class = "form-control col-12"@*, type = "file", accept = "image/png, image/jpeg, image/jpg", name = "img"*@ }
                            })
                            @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="submit" value="Ajouter" class="btn btn-success" />
                </div>
            </div>
        </div>
    </div>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

cinemafast/CinemasFAST/Views/acteurs/_Details.cshtml
@model CinemasFAST.Models.acteur

<div>
    <h4>acteur</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prenom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.langue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.langue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_naissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_naissance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lieu_naissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lieu_naissance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

    </dl>
</div>

cinemafast/CinemasFAST/Views/acteurs/_Edit.cshtml
@model CinemasFAST.Models.acteur

@using (Html.BeginForm("Edit", "acteurs"))
{
    @Html.AntiForgeryToken()
    <img src="@Html.DisplayFor(modelItem => modelItem.image)" class="float-right shadow border mr-5 mt-4" height="200" width="200" />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)

    <div class="d-flex row table-light mb-4">
        <div class="form-horizontal col-6">
            <div class="form-group col-12">
                @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group col-12">
                @Html.LabelFor(model => model.prenom, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.prenom, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.prenom, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group col-12">
                @Html.LabelFor(model => model.langue, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12">
                    @Html.DropDownList("langue", new List<SelectListItem>
                                         { new SelectListItem { Text = "Anglais", Value = "Anglais", Selected=true},
                                           new SelectListItem { Text = "Français", Value = "Français"},
                                           new SelectListItem { Text = "Espagnol", Value = "Espagnol"},
                                           new SelectListItem { Text = "Italien", Value = "Italien"},
                                           new SelectListItem { Text = "Mandarin", Value = "Mandarin"},
                                           new SelectListItem { Text = "Hindustani", Value = "Hindustani"},
                                           new SelectListItem { Text = "Arabe", Value = "Arabe"},
                                           new SelectListItem { Text = "Russe", Value = "Russe"},
                                           new SelectListItem { Text = "Portugais", Value = "Portugais"},
                                           }, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.langue, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-horizontal col-6">
            <div class="form-group col-12">
                @Html.LabelFor(model => model.date_naissance, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.date_naissance, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.date_naissance, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group col-12">
                @Html.LabelFor(model => model.lieu_naissance, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.lieu_naissance, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.lieu_naissance, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group col-12">
                @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <p class="ml-3">
        <button type="button" class="btn btn-dark">@Html.ActionLink("Retour", "Index")</button>
        <input type="submit" value="Enregistrer" class="btn btn-success" />
    </p>
}