cinemafast/CinemasFAST/Models/ViewModels/Seances_ViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CinemasFAST.Models
{
    public class Seances_ViewModel
    {
        public IEnumerable<seance> Seances { get; set; }
        public seance Seance { get; set; }
    }
}

cinemafast/CinemasFAST/Models/seance.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemasFAST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seance()
        {
            this.estpresentes = new HashSet<estpresente>();
        }
    
        public int id { get; set; }
        public System.DateTime heure_debut { get; set; }
        public System.DateTime heure_fin { get; set; }
        public string nom_seance { get; set; }
        public int id_salle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estpresente> estpresentes { get; set; }
        public virtual salle salle { get; set; }
    }
}

cinemafast/CinemasFAST/Controllers/seancesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;
using CinemasFAST.Models;

namespace CinemasFAST.Controllers
{
    public class seancesController : Controller
    {
        private cinemadbEntities db = new cinemadbEntities();
        private List<salle> salleDb = new List<salle>();
        private List<seance> seanceDb = new List<seance>();
        private List<seance> seancesRecherche = new List<seance>();

        // GET: seances
        public async Task<ActionResult> Index(int? id, bool? erreur)
        {
            List<estpresente> presentation = new List<estpresente>();
            List<film> films = new List<film>();
            if (erreur == true)
                ViewBag.erreur = "fail";
            else if (erreur == false)
                ViewBag.erreur = "succes";
            else
                ViewBag.erreur = "normal";
            int jours = DateTime.Now.Day + 6;
            DateTime jourSept = DateTime.Now.AddDays(6);
            salle salle = db.salles.Where(x => x.id == id).FirstOrDefault();
            Session["numeroSalleActuelle"] = salle.numero;
            Session["sallecourante"] = id;
            seanceDb.Clear();

            foreach (var c in db.seances)
            {
                if (c.id_salle.Equals(id) && c.heure_debut.Day >= DateTime.Now.Day && c.heure_debut.Day < jourSept.Day)
                {
                    seanceDb.Add(c);
                }
            }

            IEnumerable <seance> seanceTrier = seanceDb.OrderBy(seance => seance.heure_debut);
            Seances_ViewModel viewModel = new Seances_ViewModel();
            viewModel.Seances = await db.seances.ToListAsync();
            viewModel.Seance = new seance();
            presentation = await db.estpresentes.ToListAsync();
            films = await db.films.ToListAsync();

            string dateDebutSemaine = DateTime.Now.ToString("dd MMMM yyyy");
            string dateFinSemaine = DateTime.Now.AddDays(6).ToString("dd MMMM yyyy");

            ViewBag.Date = string.Format("Les séances du {0} au {1}.", dateDebutSemaine, dateFinSemaine);
            ViewBag.Films = films;
            ViewBag.Seance = seanceTrier;
            ViewBag.Presentation = presentation;
            ViewBag.id_film = new SelectList(db.films, "id", "titre", viewModel.Seance.id);
            return View(viewModel);
        }

        public ActionResult DateRecherche()
        {
            return View("Index");
        }

        public ActionResult Liste(int? id)
        {
            salleDb.Clear();
            using (cinemadbEntities db = new cinemadbEntities())
            {
                foreach (var c in db.salles)
                {
                    if (c.id_cinema.Equals(id))
                    {
                        salleDb.Add(c);
                    }
                }
            }
            ViewBag.Salle = salleDb;
            return View("SalleCinema");
        }

        // GET: seances/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            seance seance = db.seances.Find(id);
            if (seance == null)
            {
                return HttpNotFound();
            }
            return View(seance);
        }

        // GET: seances/Create
        public ActionResult Create()
        {
            ViewBag.id_film = new SelectList(db.films, "id", "titre");
            ViewBag.id_salle = new SelectList(db.salles, "id", "id");
            return View();
        }

        // POST: seances/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,heure_debut,heure_fin,nom_seance,id_salle")] seance seance, int salleId)
        {
            seance.id_salle = salleId;
            seance.heure_fin = seance.heure_debut.AddMinutes(30);
            string verif = Verifier(seance);
            bool isConflicted = false;
            if (verif == "")
            {
                if (ModelState.IsValid)
                {
                    isConflicted = false;
                    salle salleUtilise = db.salles.Find(seance.id_salle);
                    salleUtilise.exploitable = true;
                    db.seances.Add(seance);
                    db.SaveChanges();
                    return RedirectToAction("Index", new { id = seance.id_salle, erreur = isConflicted });
                }
                return View(seance);
            }
            else
            {
                isConflicted = true;
                return RedirectToAction("Index", new { id = seance.id_salle, erreur = isConflicted });
            }
        }

        // GET: seances/Edit/5
        public ActionResult Edit(int? id, bool? erreur)
        {
            if (erreur == null)
                erreur = false;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EstPresenter_ViewModel viewModel = new EstPresenter_ViewModel();
            viewModel.Seance = db.seances.Find(id);
            viewModel.estpresentes = db.estpresentes.Where(s => s.id_seance == id).ToList();
            estpresente presenter = new estpresente();
            presenter.id_seance = (int)id;
            viewModel.estpresente = presenter;
            if (viewModel.Seance == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_film = new SelectList(db.films, "id", "titre", viewModel.Seance.id);
            ViewBag.id_salle = new SelectList(db.salles, "id", "id", viewModel.Seance.id_salle);
            ViewBag.erreur = erreur;

            return View(viewModel);
        }

        // POST: seances/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,heure_debut,heure_fin,nom_seance,id_salle")] seance seance)
        {
            List<estpresente> presentation = new List<estpresente>();
            seance seances = db.seances.Find(seance.id);
            int temp = 0;
            if (seances.heure_debut != seance.heure_debut || seances.nom_seance != seance.nom_seance)
            {
                if (ModelState.IsValid)
                {
                    foreach (estpresente e in db.estpresentes)
                    {
                        if (e.id_seance == seance.id)
                        {
                            presentation.Add(e);
                        }
                    }

                    foreach (film f in db.films)
                    {
                        foreach (estpresente e in presentation)
                        {
                            if (f.id == e.id_film)
                            {
                                temp = f.duree;
                            }
                        }
                    }

                    seances.heure_debut = seance.heure_debut;
                    seances.heure_fin = seance.heure_debut.AddMinutes(temp + 30);
                    seances.nom_seance = seance.nom_seance;
                    bool verif = VerifierEdit(seances);
                    if (verif == true)
                    {
                        db.Entry(seances).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                    else
                    {
                        Session["ErreurAjouterFilmSeance"] = "Impossible de modifier l'heure de cette séance, car une autre séance est déjà planifiée à l'horaire.";
                    }
                }
            }
            return RedirectToAction("Edit", new { id = seance.id });
        }

        public ActionResult Delete(int id)
        {
            seance seance = db.seances.Find(id);
            //Test s'il reste des séances dans cette salle.
            List<seance> nbrSeances = db.seances.Where(s => s.id_salle == seance.id_salle).ToList();
            //S'il reste une seule séance dans cette salle cela veut dire qu'il n'y en aura plus après sa suppression on met la variable exploitable à false (pour pouvoir supprimer cette salle éventuellement).
            if (nbrSeances.Count == 1)
            {
                salle salleUtilise = db.salles.Find(seance.id_salle);
                salleUtilise.exploitable = false;
            }

            db.seances.Remove(seance);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = seance.id_salle });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //Recherche les séances entre la date de début et la date de fin que l'utilisateur a entré
        [HttpPost]
        public ActionResult RechercheDate(seance d)
        {
            d.id_salle = (int)Session["sallecourante"];

            foreach (var v in db.seances)
            {
                if (v.heure_debut > d.heure_debut && v.heure_fin <= d.heure_fin && v.id_salle == d.id_salle)
                {
                    seancesRecherche.Add(v);
                }
            }

            string date = d.heure_debut.ToString("dd MMMM yyyy");
            string date7 = d.heure_fin.ToString("dd MMMM yyyy");

cinemafast/CinemasFAST/Views/seances/Create.cshtml
@model CinemasFAST.Models.seance
@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create", "seances", new { salleId = @Session["sallecourante"] }, FormMethod.Post, null))
{
    @Html.AntiForgeryToken()
    <input type="button" class="btn btn-success m-2 openCreateSeance d-inline" value="Ajouter une séance"
           data-toggle="modal" data-target="#modalCreateSeance" />


    <div class="modal fade" id="modalCreateSeance" tabindex="-1" role="dialog" aria-labelledby="LongTitle2"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="LongTitle2">Créer une séance</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.heure_debut, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.heure_debut, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.heure_debut, null, new { @class = "text-danger" })
                        </div>
                    </div>                 
                    <div class="form-group">
                        @Html.LabelFor(model => model.nom_seance, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12">
                            @Html.DropDownList("nom_seance", new List<SelectListItem>
                                                 { new SelectListItem { Text = "Présentation régulière", Value = "Présentation régulière", Selected=true},
                                                   new SelectListItem { Text = "Présentation spéciale", Value = "Présentation spéciale"},
                                                   new SelectListItem { Text = "Avant-première", Value = "Avant-première"},
                                                   new SelectListItem { Text = "Séance privée", Value = "Séance privée"},
                                                   new SelectListItem { Text = "Film étranger", Value = "Film étranger"},
                                                   new SelectListItem { Text = "Cinéma d'ici", Value = "Cinéma d'ici"},
                                                   new SelectListItem { Text = "Les pros du court-métrage", Value = "Les pros du court-métrage"},
                                                   new SelectListItem { Text = "Lundi yoopi", Value = "Lundi yoopi"},
                                                   new SelectListItem { Text = "Mardis en folie", Value = "Mardis en folie"},
                                                   new SelectListItem { Text = "Mercredi amène ta bière", Value = "Mercredi amène ta bière"},
                                                   new SelectListItem { Text = "Jeudi sans amis", Value = "Jeudi sans amis"},
                                                   new SelectListItem { Text = "Vendredi fou", Value = "Vendredi fou"},
                                                   new SelectListItem { Text = "Samedi confettis", Value = "Samedi confettis"},
                                                   new SelectListItem { Text = "Le dimanche Saint", Value = "Le dimanche Saint"},
                                                   }, new { @class = "form-control col-12" })
                            @Html.ValidationMessageFor(model => model.nom_seance, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="submit" value="Créer" class="btn btn-success" />
                </div>
            </div>
        </div>
    </div>
}



<script src="~/Scripts/jquery-3.5.1.js"></script>
<script src="~/Scripts/jquery-ui-1.8.11.js"></script>
<link href="~/Content/jquery.datetimepicker.css" rel="stylesheet" />
<script src="~/Scripts/jquery.datetimepicker.js"></script>

<script type="text/javascript">
    var $j = jQuery.noConflict();
    $j(document).ready(function () {
        $j('input[type=datetime]').datetimepicker({
            step: 10,
            minTime: '11:50',
            maxTime: '23:00'
        });
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
}

cinemafast/CinemasFAST/Views/seances/Delete.cshtml
@model CinemasFAST.Models.seance

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Êtes-vous sur de vouloir supprimer cette séance?</h3>
<div>
    <h4>seance</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.heure_debut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.heure_debut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.heure_fin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.heure_fin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nom_seance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom_seance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.film.titre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.film.titre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.salle.taille_ecran)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.salle.taille_ecran)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.salle.id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.salle.id)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

cinemafast/CinemasFAST/Views/seances/Details.cshtml
@model CinemasFAST.Models.seance

@{
    ViewBag.Title = " ";
}

<h2>Details</h2>

<div>
    <h4>seance</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.heure_debut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.heure_debut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.heure_fin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.heure_fin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nom_seance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom_seance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.film.titre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.film.titre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.salle.taille_ecran)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.salle.taille_ecran)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.salle.id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.salle.id)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

cinemafast/CinemasFAST/Views/seances/Edit.cshtml
@model CinemasFAST.Models.EstPresenter_ViewModel

@{ ViewBag.Title = " "; }

<div class="jumbotron">
    <h2>Liste des films à la séance @Model.Seance.id <span class="bg-dark rounded text-warning p-2 float-right shadow">Cinéma @Session["nomCinemaActuel"], salle @Session["numeroSalleActuelle"]</span></h2>
    <h4 class="text-danger">@Session["ErreurAjouterFilmSeance"]</h4>
</div>

<div class="d-flex col-12">
    <div class="col-8">
        @Html.Partial("~/Views/estpresentes/_Index.cshtml", Model.estpresentes)
    </div>

    <div class="col-4">
        @Html.Partial("~/Views/seances/_Edit.cshtml", Model.Seance)
    </div>
</div>

<div>
    @Html.Partial("~/Views/estpresentes/_Create.cshtml", Model.estpresente)
</div>

@{ //Permet d'effacer le message d'erreur si on reload ou change de page.
    Session["ErreurAjouterFilmSeance"] = ""; }

cinemafast/CinemasFAST/Views/seances/Index.cshtml
@model CinemasFAST.Models.Seances_ViewModel

@{
    ViewBag.Title = "Seances";

}
    <div class="jumbotron">
        <h2>Seances <span class="bg-dark rounded text-warning p-2 float-right shadow">Cinéma @Session["nomCinemaActuel"], salle @Session["numeroSalleActuelle"] </span></h2>
        <h4>
            @ViewBag.date
        </h4>

        @if (ViewBag.erreur == "fail")
        {
            <h4 class="text-danger">Impossible, il y a déjà une représentation durant cette période.</h4>
        }
        else if (ViewBag.erreur == "succes")
        {
            <h4 class="text-success">La séance a été créée avec succès!</h4>
        }
    </div>

<div class="d-flex justify-content-start">
    @Html.Partial("~/Views/seances/Create.cshtml", Model.Seance)
    @Html.Partial("~/Views/seances/Recherche.cshtml", Model.Seance)
</div>

<div>
    @Html.Partial("~/Views/seances/_Index.cshtml", Model.Seances)
</div>

<div>
    @Html.ActionLink("Retour", "Edit", "cinemas", new { id = Session["idCinemaActuel"] }, new { @class = "btn btn-dark" })
</div>
@{

    //Permet d'effacer le message d'erreur si on reload ou change de page.
    Session["createErreurSeance"] = "";
}

cinemafast/CinemasFAST/Views/seances/Recherche.cshtml
@model CinemasFAST.Models.seance
@{
    ViewBag.Title = "Recherche";
}

@using (Html.BeginForm("RechercheDate", "seances", FormMethod.Post))
{
    <input type="button" class="btn btn-info my-2 openRechercheSeance" value="Recherche" 
           data-toggle="modal" data-target="#modalRecherche" />

    <div class="modal fade" id="modalRecherche" tabindex="-1" role="dialog" aria-labelledby="LongTitle4" 
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="LongTitle4">Filtre de recherche</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.heure_debut, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.heure_debut, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.heure_debut, null, new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.heure_fin, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.heure_fin, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.heure_fin, null, new { @class = "text-danger" })
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <input type="submit" value="Rechercher" class="btn btn-info" />
                </div>
            </div>
        </div>
    </div>
}


<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/jquery-ui-1.8.11.js"></script>
<link href="~/Content/jquery.datetimepicker.css" rel="stylesheet" />
<script src="~/Scripts/jquery.datetimepicker.js"></script>

<script type="text/javascript">
    var $j = jQuery.noConflict();
    $j(document).ready(function () {
        $j('input[type=datetime]').datetimepicker({
            step: 10,
            minTime: '11:50',
            maxTime: '23:00'
        });
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
}

cinemafast/CinemasFAST/Views/seances/SalleCinema.cshtml
@model IEnumerable<CinemasFAST.Models.seance>

@{
    ViewBag.Title = "Salle";
}
<div class="list">
    <h2>SalleCinema</h2>
</div>

<table class="table">
    <tr>
        <th>
            Numéro de salle
        </th>
        <th>
            Nombre de place
        </th>
        <th>
            Salle exploitable (True / False)
        </th>
        <th>
            Séances de cette salle
        </th>
    </tr>
    @foreach (var item in ViewBag.Salle)
    {
        <tr>
            <td>
                @item.numero
            </td>
            <td>
                @item.nbr_places
            </td>
            <td>
                @item.exploitable
            </td>
            @if (item.exploitable == true)
            {
                <td>
                    @Html.ActionLink("Séances", "Seances", new { id = item.id })
                </td>
            }
            <br />
        </tr>
    }

</table>

cinemafast/CinemasFAST/Views/seances/SeanceRechercher.cshtml
@model IEnumerable<CinemasFAST.Models.seance>

@{
    ViewBag.Title = "SeanceRechercher";
}
<div class="jumbotron">
    <h2>Seances trouvées <span class="bg-dark rounded text-warning p-2 float-right shadow">Cinéma @Session["nomCinemaActuel"], salle @Session["numeroSalleActuelle"] </span></h2>
    <h4> @ViewBag.date </h4>
</div>

<div>
    @Html.ActionLink("Recherche", "Recherche")

    <table class="table table-light table-striped table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.heure_debut)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.heure_fin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nom_seance)
            </th>
            <th></th>
        </tr>

        @foreach (var item in ViewBag.SeanceRechercher)
        {
            <tr>
                <td>
                    @item.heure_debut
                </td>
                <td>
                    @item.heure_fin
                </td>
                <td>
                    @item.nom_seance
                </td>
                <td>
                    @Html.ActionLink(" ", "Edit", new { id = item.id }, new { @class = "btn btn-sm btn-info fa fa-info-circle" })
                    @Html.ActionLink(" ", "Delete", new { id = item.id }, new { @class = "btn btn-sm btn-danger fa fa-trash" })
                </td>
            </tr>
        }
    </table>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Retour", "Index", "seances", new { id = Session["sallecourante"] }, new { @class = "btn btn-dark" })
        </div>
    </div>
</div>

cinemafast/CinemasFAST/Views/seances/_Edit.cshtml
@model CinemasFAST.Models.seance

@{ ViewBag.Title = "Edit"; }

<script src="~/Scripts/jquery-3.5.1.js"></script>
<script src="~/Scripts/jquery-ui-1.8.11.js"></script>
<link href="~/Content/jquery.datetimepicker.css" rel="stylesheet" />
<script src="~/Scripts/jquery.datetimepicker.js"></script>

<script type="text/javascript">
    var $j = jQuery.noConflict();
    $j(document).ready(function () {
        $j('input[type=datetime]').datetimepicker({
            step: 10,
            minTime: '11:50',
            maxTime: '23:00'
        });
    });
</script>

@using (Html.BeginForm("Edit", "seances"))
{
    @Html.AntiForgeryToken()

    <div class="jumbotron">
        <h4> Séance </h4>
        @if (ViewBag.erreur)
        {
            <h4 class="text-danger">Impossible de planifier ces séances, il y a un conflit d'horaire avec d'autres séances.</h4>
        }
    </div>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)

    <div class="form-group">
        @Html.LabelFor(model => model.heure_debut, htmlAttributes: new { @class = "control-label col-md-12" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.heure_debut, new { htmlAttributes = new { @class = "form-control col-12" } })
            @Html.ValidationMessageFor(model => model.heure_debut, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.nom_seance, htmlAttributes: new { @class = "control-label col-md-12" })
        <div class="col-md-12">
            @Html.DropDownList("nom_seance", new List<SelectListItem>
                                 { new SelectListItem { Text = "Présentation régulière", Value = "Présentation régulière", Selected=true},
                                   new SelectListItem { Text = "Présentation spéciale", Value = "Présentation spéciale"},
                                   new SelectListItem { Text = "Avant-première", Value = "Avant-première"},
                                   new SelectListItem { Text = "Séance privée", Value = "Séance privée"},
                                   new SelectListItem { Text = "Film étranger", Value = "Film étranger"},
                                   new SelectListItem { Text = "Cinéma d'ici", Value = "Cinéma d'ici"},
                                   new SelectListItem { Text = "Les pros du court-métrage", Value = "Les pros du court-métrage"},
                                   new SelectListItem { Text = "Lundi yoopi", Value = "Lundi yoopi"},
                                   new SelectListItem { Text = "Mardis en folie", Value = "Mardis en folie"},
                                   new SelectListItem { Text = "Mercredi amène ta bière", Value = "Mercredi amène ta bière"},
                                   new SelectListItem { Text = "Jeudi sans amis", Value = "Jeudi sans amis"},
                                   new SelectListItem { Text = "Vendredi fou", Value = "Vendredi fou"},
                                   new SelectListItem { Text = "Samedi confettis", Value = "Samedi confettis"},
                                   new SelectListItem { Text = "Le dimanche Saint", Value = "Le dimanche Saint"},
                                   }, new { @class = "form-control col-12" })
            @Html.ValidationMessageFor(model => model.nom_seance, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="d-flex col-12">
            <input type="submit" value="Enregistrer" class="btn btn-success mr-2 py-n0" />
            @Html.ActionLink("Récurrente (7 jours)", "CreateSemaine", new { id = Model.id }, new { @class = "btn btn-secondary" })
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}