cinemafast/CinemasFAST/Controllers/filmsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Data.SqlClient;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Windows;
using CinemasFAST.Models;
using CinemasFAST.Models.ViewModels;

namespace CinemasFAST.Controllers
{
    public class filmsController : Controller
    {
        private cinemadbEntities db = new cinemadbEntities();

        // GET: films
        public async Task<ActionResult> Index(bool? erreur, bool? erreurDel, bool? successImport, string searchString)
        {
            if (erreur == true)
                ViewBag.erreur = "fail";
            else if (erreur == false && successImport == true)
                ViewBag.erreur = "succesImport";
            else if (erreur == false && successImport == null)
                ViewBag.erreur = "succes";
            else
                ViewBag.erreur = "normal";
            if (erreurDel == true)
                ViewBag.erreurDel = "fail";
            else if (erreurDel == false)
                ViewBag.erreurDel = "succes";            
            else
                ViewBag.erreurDel = "normal";

            IndexFilm_ViewModel viewModel = new IndexFilm_ViewModel();
            ViewBag.id_genre = new SelectList(db.genres, "id", "nom");
            ViewBag.type_film = new List<string> { "Standard", "Court métrage", "Promotionnel" };


            if (!String.IsNullOrEmpty(searchString))
            {
                viewModel.Films = await db.films.Where(s => s.titre.Contains(searchString)
                                       || s.description.Contains(searchString)).ToListAsync();
                ViewBag.searchRequest = true;
            }
            else
            {
                viewModel.Films = await db.films.Include(f => f.genre).ToListAsync();
                ViewBag.searchRequest = false;
            }

            ModelState.Clear();
            return View(viewModel);
        }

        // GET: films/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RolesDirections_ViewModel viewModel = getViewModelEdit(id);
            if (viewModel.Film == null)
            {
                return HttpNotFound();
            }
            return View(viewModel);
        }

        // GET: films/Create
        public ActionResult Create()
        {
            ViewBag.searchRequest = false;
            return View();
        }

        // POST: films/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,titre,description,annee,duree,note,nbr_votes,revenue,id_genre,image,type")] film film)
        {
            bool isConflicted = false;
            if (ModelState.IsValid)
            {
                isConflicted = false;
                db.films.Add(film);
                ViewBag.id_genre = new SelectList(db.genres, "id", "nom", film.id_genre);
                db.SaveChanges();
            }
            else
            {
                isConflicted = true;
            }
            return RedirectToAction("Index", new { erreur = isConflicted });
        }

        // GET: films/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            film film = db.films.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_genre = new SelectList(db.genres, "id", "nom", film.id_genre);
            return View(film);
        }

        // POST: films/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,titre,description,annee,duree,note,nbr_votes,revenue,id_genre,type,image")] film film)
        {

            if (ModelState.IsValid)
            {
                Session["editSuccess"] = "Film modifié avec succès!";
                db.Entry(film).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = film.id });
            }
            ViewBag.id_genre = new SelectList(db.genres, "id", "nom", film.id_genre);
            RolesDirections_ViewModel viewModel = getViewModelEdit(film.id);
            return View("Details", viewModel);
        }

        //Remplis un viewmodel qui servira aux vue partiels qui sont a l'interieurs du detils du film
        public RolesDirections_ViewModel getViewModelEdit(int? id)
        {
            RolesDirections_ViewModel viewModel = new RolesDirections_ViewModel();
            viewModel.Role = new role();
            viewModel.Direction = new direction();
            viewModel.Film = db.films.Find(id);
            viewModel.Roles = db.roles.Where(r => r.id_film == id).ToList();
            viewModel.Directions = db.directions.Where(d => d.id_film == id).ToList();

            ViewBag.id_film = new SelectList(db.films.Where(x => x.id == id), "id", "titre", viewModel.Film.id);
            ViewBag.id_acteur = new SelectList(db.acteurs, "id", "nom", viewModel.Role.id_acteur);
            ViewBag.id_directeur = new SelectList(db.directeurs, "id", "nom", viewModel.Direction.id_directeur);
            ViewBag.id_genre = new SelectList(db.genres, "id", "nom", viewModel.Film.id_genre);
            ViewBag.titre = db.films.Find(id).titre;
            ViewBag.film_actuel = viewModel.Film.titre;

            return viewModel;
        }

        // GET: films/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            film film = db.films.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }


        public ActionResult DeleteConfirmed(int id)
        {

            film film = db.films.Find(id);
            //Supprime les directions et les roles associer au film
            List<direction> directions = db.directions.Where(d => d.id_film == id).ToList();
            List<role> roles = db.roles.Where(r => r.id_film == id).ToList();
            List<seance> seances = db.seances.Where(r => r.id == id).ToList();
            List<estpresente> estpresente = db.estpresentes.Where(x => x.id_film == id).ToList();
            int nbSeance = estpresente.Count();
            bool isConflicted = false;

            if (seances.Count() != 0)
            {
                isConflicted = true;
            }
            else
            {
                isConflicted = false;

                foreach (role r in roles)
                {
                    db.roles.Remove(r);
                }
                foreach (direction d in directions)
                {
                    db.directions.Remove(d);
                }
                foreach (estpresente e in estpresente)
                {
                    db.estpresentes.Remove(e);
                }
                db.films.Remove(film);
                db.SaveChanges();
            }
            return RedirectToAction("Index", new { erreurDel = isConflicted });
        }

        public ActionResult deleteRole(int id)
        {
            return RedirectToAction("DeleteConfirmedToFilm", "roles", new { id = id });
        }

        public ActionResult deleteDirection(int id)
        {
            return RedirectToAction("DeleteConfirmedToFilm", "directions", new { id = id });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Importation d'un fichier des films       

        [HttpPost]
        public ActionResult ImportFile(HttpPostedFileBase postedFile)
        {
            string filePath = string.Empty;
            if (postedFile != null)
            {
                string path = Server.MapPath("~/Uploads/");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                filePath = path + Path.GetFileName(postedFile.FileName);
                string extension = filePath.Substring(Math.Max(0, filePath.Length - 4));
                if (extension != ".csv")
                {
                    Session["ErrorUponCreateFilm"] = "Le fichier importé doit être de type .csv";
                    return RedirectToAction("Index");
                }
                AjoutFilms(filePath);
                AjoutDirecteurs(filePath);
                AjoutActeurs(filePath);
                try
                {
                    db.SaveChanges();
                }
                catch (DbEntityValidationException e)
                {
                    foreach (var eve in e.EntityValidationErrors)
                    {
                        Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                            eve.Entry.Entity.GetType().Name, eve.Entry.State);
                        foreach (var ve in eve.ValidationErrors)
                        {

cinemafast/CinemasFAST/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cinéma FAST</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="h-100">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content vh-100">
        @RenderBody()

    </div>
    <footer class="container body-content">
        <p class="text-black-50 pt-3">&copy; @DateTime.Now.Year - Cinéma FAST</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

cinemafast/CinemasFAST/Views/Shared/_LayoutLoggedIn.cshtml
@{
    if (Session["login"] == null)
    {
        try
        {
            Response.Redirect("~/Home/Login");
        }
        catch (Exception e)
        {
            System.Diagnostics.Debug.WriteLine(e.Message);
        }
    }
    ViewBag.controller = HttpContext.Current.Request.RequestContext.RouteData.Values["Controller"].ToString();
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cinéma FAST</title>
    <link rel="shortcut icon" type="image/png" href="@Url.Content("~/Content/favicon.png")" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="bg-light">
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        <div class="container d-flex">
            <a href="@Url.Action("Index", "Home")" class="mr-3 ml-n3">
                <img src="@Url.Content("~/Uploads/MCgH6s2.png")" alt="Logo du Cinéma" height="40" />
            </a>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Administration
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <h5 class="nav-header bg-secondary text-light mt-0">Listes d'objets</h5>
                            @Html.ActionLink("Cinémas", "Index", "cinemas", null, new { @class = "nav-link nav-hover text-dark" })
                            @Html.ActionLink("Films", "Index", "films", null, new { @class = "nav-link nav-hover text-dark" })
                            @Html.ActionLink("Directeurs", "Index", "directeurs", null, new { @class = "nav-link text-dark nav-hover" })
                            @Html.ActionLink("Acteurs", "Index", "acteurs", null, new { @class = "nav-link text-dark nav-hover" })

                            @if (Session["id"] != null && Session["type"].Equals("admin"))
                            {
                                <h5 class="nav-header mt-0 bg-secondary text-light">Outils administrateur</h5>
                                @Html.ActionLink("Liste des comptes", "Index", "profils", null, new { @class = "nav-link text-dark nav-hover" })
                                @Html.ActionLink("Créer un compte", "Create", "profils", null, new { @class = "nav-link text-dark nav-hover" })
                            }
                        </div>
                    </li>
                </ul>
            </div>

            <div class="navbar-collapse collapse flex-row-reverse col-1">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Bonjour, @if (Session["login"] != null)
                            {@Session["login"].ToString().Split(' ')[0]}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @Html.ActionLink("Mon compte", "Edit", "profils", new { id = Session["id"] }, new { @class = "nav-link text-dark nav-hover" })
                            <a href="#" data-toggle="modal" , data-target="#modalDeconnexion" class="nav-link text-dark nav-hover">Déconnexion</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    @*Déconnexion*@
    <div class="modal fade" id="modalDeconnexion" tabindex="-1" role="dialog" aria-labelledby="CenterTitle"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="LongTitle1">Déconnexion</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h5 class="text-black-50">Voulez-vous vraiment vous déconnecter?</h5>
                </div>

                <div class="modal-footer">
                    <button class="btn btn-secondary" data-dismiss="modal">Non</button>
                    @Html.ActionLink("Oui", "Disconnect", "Home", null, new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>
    </div>

    <div class="container body-content bg-white pb-3 rounded shadow shadow-sm">
        @RenderBody()
    </div>
    <footer class="container body-content">
        <p class="text-black-50 pt-3">&copy; @DateTime.Now.Year - Cinéma FAST</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", false)
</body>
</html>

cinemafast/CinemasFAST/Views/Shared/_LayoutLoggedOut.cshtml
@{ViewBag.controller = HttpContext.Current.Request.RequestContext.RouteData.Values["Controller"].ToString();}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cinéma FAST</title>
    <link rel="shortcut icon" type="image/png" href="@Url.Content("~/Content/favicon.png")" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        <div class="container">
            <a href="@Url.Action("Index", "Home")" class="mr-3 ml-n3">
                <img src="@Url.Content("~/Uploads/MCgH6s2.png")" alt="Logo du Cinéma" height="40" />
            </a>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav mr-auto">
                </ul>
                @Html.ActionLink("Connexion", "Login", "Home", null, new { @class = "navbar-brand", data_toggle = "modal", data_target = "#modalConnexion" })
            </div>
        </div>
    </nav>
    <div class="container body-content bg-white pb-3 rounded shadow shadow-sm">
        @RenderBody()

    </div>
    <footer class="container body-content">
        <p class="text-black-50 pt-3">&copy; @DateTime.Now.Year - Cinéma FAST</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>