cinemafast/CinemasFAST/Models/role.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemasFAST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public int id { get; set; }
        public int id_film { get; set; }
        public int id_acteur { get; set; }
        public string nom_personnage { get; set; }
    
        public virtual acteur acteur { get; set; }
        public virtual film film { get; set; }
    }
}

cinemafast/CinemasFAST/Controllers/rolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CinemasFAST.Models;

namespace CinemasFAST.Controllers
{
    public class rolesController : Controller
    {
        private cinemadbEntities db = new cinemadbEntities();

        // GET: roles
        public ActionResult Index()
        {
            var roles = db.roles.Include(r => r.acteur).Include(r => r.film);
            return View(roles.ToList());
        }

        // GET: roles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            role role = db.roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // GET: roles/Create
        public ActionResult Create()
        {
            ViewBag.id_acteur = new SelectList(db.acteurs, "id", "nom");
            ViewBag.id_film = new SelectList(db.films, "id", "titre");
            return View();
        }

        // POST: roles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,id_film,id_acteur,nom_personnage")] role role)
        {
            if (ModelState.IsValid)
            {
                db.roles.Add(role);
                db.SaveChanges();
                return RedirectToAction("Details", "films", new { id = role.id_film });
            }

            ViewBag.id_acteur = new SelectList(db.acteurs, "id", "nom", role.id_acteur);
            ViewBag.id_film = new SelectList(db.films, "id", "titre", role.id_film);
            Session["roleErreur"] = "Le nom du personnage doit être entré.";
            return RedirectToAction("Details", "films", new { id = role.id_film });
        }

        // GET: roles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            role role = db.roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_acteur = new SelectList(db.acteurs, "id", "nom", role.id_acteur);
            ViewBag.id_film = new SelectList(db.films, "id", "titre", role.id_film);
            return View(role);
        }

        // POST: roles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,id_film,id_acteur,nom_personnage")] role role)
        {
            if (ModelState.IsValid)
            {
                db.Entry(role).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_acteur = new SelectList(db.acteurs, "id", "nom", role.id_acteur);
            ViewBag.id_film = new SelectList(db.films, "id", "titre", role.id_film);
            return View(role);
        }

        // GET: roles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            role role = db.roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        public ActionResult DeleteConfirmedToFilm(int id)
        {
            role role = db.roles.Find(id);
            film film = db.films.Find(role.id_film);
            db.roles.Remove(role);
            db.SaveChanges();
            return RedirectToAction("Details", "films", new { id = film.id });
        }

        public ActionResult DeleteConfirmedToActeur(int id)
        {
            role role = db.roles.Find(id);
            acteur acteur = db.acteurs.Find(role.id_acteur);
            db.roles.Remove(role);
            db.SaveChanges();
            return RedirectToAction("Details", "acteurs", new { id = acteur.id });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

cinemafast/CinemasFAST/Views/roles/_Create.cshtml
@model CinemasFAST.Models.role

@using (Html.BeginForm("Create", "roles"))
{
    @Html.AntiForgeryToken()
    <div class="mb-3">
        <input type="button" value="Ajouter un rôle" class="btn btn-success"
               data-toggle="modal" data-target="#exampleModal" />
    </div>

    <div class="modal fade" id="exampleModal" data-backdrop="false" tabindex="-1" role="dialog" aria-labelledby="Longtitle3" 
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="Longtitle3">Créer un rôle</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group d-none">
                        @Html.LabelFor(model => model.id_film, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12 disabled">
                            @Html.DropDownList("id_film", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.id_film, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.id_acteur, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12">
                            @Html.DropDownList("id_acteur", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.id_acteur, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.nom_personnage, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.nom_personnage, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.nom_personnage, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="submit" value="Ajouter" class="btn btn-success" />
                    <button type="button" class="btn btn-secondary">@Html.ActionLink("Créer un acteur", "Create", "acteurs", null, null)</button>
                </div>
            </div>
        </div>
    </div>
}

cinemafast/CinemasFAST/Views/roles/_Index.cshtml
@model IEnumerable<CinemasFAST.Models.role>
@{
    var controller = HttpContext.Current.Request.RequestContext.RouteData.Values["Controller"].ToString();
}

    <div class="scrollable">
        <table class="table table-light table-striped table-hover sortable">
            <thead>
                <tr>
                    @if (!controller.Equals("acteurs"))
                    {
                        <th>
                            @Html.DisplayNameFor(model => model.acteur.nom)
                        </th>
                    }
                    <th>
                        @Html.DisplayNameFor(model => model.nom_personnage)
                    </th>
                    @if (controller.Equals("acteurs"))
                    {
                        <th>
                            @Html.DisplayNameFor(model => model.film)
                        </th>
                    }
                    <th data-defaultsort='disabled'></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        @if (!controller.Equals("acteurs"))
                        {
                            <td>
                                <u>
                                    @Html.ActionLink(item.acteur.prenom + " " + item.acteur.nom, "Details", "acteurs", new { id = item.id_acteur }, new { @class = "text-dark" })
                                </u>
                            </td>
                        }
                        <td>
                            @Html.DisplayFor(modelItem => item.nom_personnage)
                        </td>
                        @if (controller.Equals("acteurs"))
                        {
                            <td>
                                @Html.DisplayFor(model => item.film.titre)
                            </td>
                        }
                        <td>
                            @Html.ActionLink(" ", "deleteRole", new { id = item.id }, new { @class = "btn btn-sm btn-danger fa fa-trash", @onclick = "return confirm('Voulez-vous supprimer ce cinéma?');" })
                        </td>
                    </tr>
                }

                @if (Model.Count() == 0)
                {
                    if (!controller.Equals("acteurs"))
                    {
                        <tr>
                            <td colspan="4" class="font-italic h5 text-secondary">Ajouter un rôle afin qu'il soit affiché ici.</td>
                        </tr>
                    }
                    else
                    {
                        <tr>
                            <td colspan="4" class="font-italic h5 text-secondary">Cet acteur a joué dans aucun film pour le moment.</td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>